# docker-compose.yml
version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql   # 컨테이너 재시작해도 데이터 유지

  redis:
    image: redis:7.2-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: