spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL   # MySQL 호환 모드
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false